name: 'Build exporter'
description: 'Build and release an exporter'
inputs: 
  exporter:
    description: 'Exporter name'
    required: true
    default: ''
  artifactory_token:
    description: 'Artifactory token'
    required: true
    default: ''
  artifactory_username:
    description: 'Artifactory username'
    required: true
    default: ''
  tag_name:
    description: 'Tag name'
    required: true
    default: ''
  target:
    description: 'Target name'
    required: false
    default: ''
  sysdig_secure_token:
    description: 'Sysdig Secure token'
    required: true
    default: ''
  dockerfile:
    description: 'Dockerfile destination'
    required: false
    default: 'Dockerfile'
  repository:
    description: 'Repository url'
    required: true
    default: ''
  repository_folder:
    description: 'Repository folder where it goes the image'
    required: false
    default: 'sysdig-artifact-registry-dev/gar-docker/monitor/exporters'
branding:
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Login to Artifactory
      uses: docker/login-action@v2 
      with:
        registry: ${{ inputs.repository }}
        username: ${{ inputs.artifactory_username }}
        password: ${{ inputs.artifactory_token }}
    - name: Build image
      shell: bash
      run: |
        docker build --label release=${{ inputs.tag_name }} -f ${{ inputs.dockerfile }} --target ${{ inputs.target }} -t ${{ inputs.exporter }}:latest .
        docker tag ${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:latest
    - name: Scan local image
      id: scan-local
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: ${{ inputs.exporter }}
        sysdig-secure-token: ${{ inputs.sysdig_secure_token }}
        ignore-failed-scan: true
        input-type: docker-daemon
        run-as-user: root
    - name: Publish docker ubi image as ubi and as latest
      if: ${{ inputs.target }} == 'ubi'
      shell: bash
      run: |
        docker tag ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
        docker tag ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}
        docker push ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
        docker push ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:latest
        docker push ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}
    - name: Publish docker scratch image
      if: ${{ inputs.target }} != 'ubi'
      shell: bash
      run: |
        docker tag ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
        docker push ${{ inputs.repository }}/${{ inputs.repository_folder }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
